### ISSUE TITLE
Any plans to support meta fields?

### ISSUE THREAD

**Issue by bzbetty** [Code-Hex/graphql-codegen-typescript-validation-schema#148]
It seems like a number of core people in the graphql spec community are starting to push the idea of meta fields instead of using schema directives.

https://www.youtube.com/watch?v=c1oa7p73rTw
https://youtu.be/gVCszBu_aJI

Essentially boils down to having an extra fields on all types called meta where you can add in things like validation metadata.

Have you seen this and have any thoughts on getting it implemented in this library?

It's more designed for an introspection approach rather than an SDL one from what I can tell.

**Comment by Code-Hex** [comment]
@bzbetty Thanks for commenting your knowledge for metadata.

I didn't know that. But interesting!

Do you know where are any proposal issues referred to it on the GraphQL spec?

If the specifications are not nearly finalized, I think it is still too early to consider for it.

**Comment by bzbetty** [comment]
The main conversation seems to be https://github.com/graphql/graphql-spec/issues/300 however it has been going for quite a few years.

I think rather than supporting a specific proposal it would make sense to try extend what you're already doing with the directivesConfig.  

I'm assuming this plugin only supports SDL and not introspection? (as there's no convension for exposing directives in introspection).  Please correct me if I'm wrong on this one though (tbh i'm not sure if that's abstracted completely by codegen already and you don't have access).

So what I'm suggesting is a way of pulling arbritrary data out of the introspection structure, as the spec already supports modifying built in introspection types.

```
query {
  __schema {
    type {
      name
      meta { validation { name args } }
      field { meta { validation { name args } } }
    }
  }
}

```

Given meta could be on a type, field or probalby various other types I'm not quite sure how you'd map that back to yaml

eg currently you do

```
  directives:    
        required:
          msg: required
        constraint:
          minLength: min
          # Replace $1 with specified `startsWith` argument value of the constraint directive
          startsWith: ["matches", "/^$1/"]
          format:
            email: email
```

it'd have to modify the introspection queries which again feel like it might be too low level for a plugin to be able to do?
