### ISSUE TITLE
Use `unknown` as the default any type rather than literal `{}`

### ISSUE THREAD

**Issue by chrisui** [Code-Hex/graphql-codegen-typescript-validation-schema#17]
## Context

Referencing the following code:

https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/blob/8105f2b51dd62241f6daae8abc97675374fae5b7/src/zod/index.ts#L36

Currently, with a custom scalar `Date: Date` (see graphql-codegen `scalarMap` config) we end up with type errors such as `"{} is missing properties from Date toLocaleString, ..."` etc.

## Proposal

Replace `{}` with `unknown` would allow consumers of this library to cast as neccessary.

**Comment by wiksien** [comment]
I will fix that.

**Comment by Code-Hex** [comment]
@chrisui Thanks for your reporting!
This plugin has been developing under the assumption that it inherited the settings of the typescript plugin. for example

```yaml
example/zod/schemas.ts:
    plugins:
      - ./dist/main/index.js:
          schema: zod
          scalars:
            Date: Date
```

It was supposed to create a schema that takes into account the Date object. This is a bug and will be fixed.
