### ISSUE TITLE
Bind two arguments to one constraint

### ISSUE THREAD

**Issue by 0Lucifer0** [Code-Hex/graphql-codegen-typescript-validation-schema#170]
Hi, 
I'm wondering if there is currently anyway to associate two arguments to one constraint ? 

example:
`@StringLength(minValue: 50, maxValue:100, errorMessage:"some error message")`
that would generate
`yup.string().defined().min(50, "some error message"").max(100, "some error message")`

If that's not possible currently, is there any idea on how a configuration for this would look like so I can look at implementing it when I understand a bit better how this plugin works?

**Comment by Code-Hex** [comment]
@0Lucifer0 Thanks for asking me!

Maybe like this? If not possible, a fix maybe may need to be supported.

```yaml
config:
      schema: yup
      directives:
        constraint:
          StringLength:
            ["min", "$1", "$2"]
            ["max", "$1", "$2"]
```
