### ISSUE TITLE
How to define complex scalarSchemas? (for JSON scalars)

### ISSUE THREAD

**Issue by AndKiel** [Code-Hex/graphql-codegen-typescript-validation-schema#214]
I have `JSON` and `JSONObject` scalars in GraphQL schema (from the https://github.com/taion/graphql-type-json package).

Given I have types defined in a file:

```typescript
export type JsonObject = { [Key in string]?: JsonValue };
export type JsonValue = JsonObject | JsonValue[] | boolean | number | string | null;
```

When generating TypeScript code, I could do this:

```yml
overwrite: true
schema: "./schema.graphql"
documents: "app/**/*.graphql"
generates:
  app/__generated__/sdk.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-graphql-request"
    config: &base-config
      scalars:
        JSON: "../types/json#JsonValue" # <-- this
        JSONObject: "../types/json#JsonObject" # <-- and this
      strictScalars: true
```

And it would generate correct imports inside the `sdk.ts` file and use them:

```typescript
import { JsonValue } from '../types/json';
import { JsonObject } from '../types/json';
```

I cannot find any way to do something similar for `scalarSchemas`. If I added the zod schemas for my JSON types like this:

```typescript
export const jsonValueSchema: z.ZodType<JsonValue> = z.lazy(() =>
  z.union([z.record(jsonValueSchema), z.array(jsonValueSchema), z.boolean(), z.number(), z.string(), z.null()]),
);
export const jsonObjectSchema = z.record(jsonValueSchema);
```
I'd like to be able to do:

```yml
  app/__generated__/schemas.ts:
    plugins:
      - "typescript-validation-schema"
    config:
      <<: *base-config
      importFrom: ./sdk
      scalarSchemas:
        JSON: "../types/json#jsonValueSchema" # <-- this
        JSONObject: "../types/json#jsonObjectSchema" # <-- and this
      schema: zod
```

Unfortunately, it just puts the value as-is, making generated code invalid.

#### EDIT#1
Obviously, I can do this:
```yml
overwrite: true
schema: "./schema.graphql"
documents: "app/**/*.graphql"
generates:
  app/__generated__/sdk.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-graphql-request"
      - "typescript-validation-schema"
    config:
      scalars:
        JSON: "../types/json#JsonValue"
        JSONObject: "../types/json#JsonObject"
      scalarSchemas:
        JSON: "<z.ZodType<JsonValue>>z.lazy(() => {const jsonValueSchema: z.ZodType<JsonValue> = z.lazy(() => z.union([z.record(jsonValueSchema), z.array(jsonValueSchema), z.boolean(), z.number(), z.string(), z.null()])); return jsonValueSchema;})"
        JSONObject: "z.record(<z.ZodType<JsonValue>>z.lazy(() => {const jsonValueSchema: z.ZodType<JsonValue> = z.lazy(() => z.union([z.record(jsonValueSchema), z.array(jsonValueSchema), z.boolean(), z.number(), z.string(), z.null()])); return jsonValueSchema;}))"
      schema: zod
      strictScalars: true
```

and generate a single file. Yet, the declaration itself becomes unreadable and generated code repetitive (and also unreadable). :/

**Comment by Code-Hex** [comment]
@AndKiel Thank you for creating a new issue!

Your Edit 1 is exactly. Currently, the `scalarSchemas` just supported writing validation schema directly.

I'd like to confirm what are you expected. Do you want to import zod schema which is you prepared in typescript file?

> Yet, the declaration itself becomes unreadable and generated code repetitive (and also unreadable). :/

**Comment by AndKiel** [comment]
> I'd like to confirm what are you expected. Do you want to import zod schema which is you prepared in typescript file?

Yes. I'd like `scalarSchemas` to support the same notation as `scalars` and allow importing zod schemas from a file. It would be very useful and allow very clean declarations. The last snippet before Edit#1 shows what I mean.

**Comment by Code-Hex** [comment]
@AndKiel Thanks for your confirmation.
I understand what you want. Actually, this plugin parses only GraphQL Schema, not TypeScript. So the support is very difficult for me.

However, I may help you with this solution.

1. Use `@graphql-codegen/add` package and add config for this package like this.

```yaml
- add:
    content: "import { jsonValueSchema, jsonObjectSchema } from '../types/json'"
```

2. Modify your `scalarSchemas` configuration like this.

```yaml
scalarSchemas:
        JSON: jsonValueSchema
        JSONObject: jsonObjectSchema
```

3. Generate your code!
