### ISSUE TITLE
How should nested inputs be handled?

### ISSUE THREAD

**Issue by earnubs** [Code-Hex/graphql-codegen-typescript-validation-schema#384]

**Comment by Code-Hex** [comment]
@earnubs Thank you for making this issue!

Some extracts from the README This setting allows you to configure how the validation schema is assigned to the scalar.

### `scalarSchemas`

type: `ScalarSchemas`

Extends or overrides validation schema for the built-in scalars and custom GraphQL scalars.

#### yup schema

```yml
config:
  schema: yup
  scalarSchemas:
    Date: yup.date()
    Email: yup.string().email()
```

#### zod schema

```yml
config:
  schema: zod
  scalarSchemas:
    Date: z.date()
    Email: z.string().email()
```

---

I think your configuration is right. But I don't understand what does this mean?
>  the nested inputs

I would be grateful if you could provide us with your schema set as a scalar and the TypeScript code generated for it to better understand it.

**Comment by earnubs** [comment]
Made up example:

```
BusinessInput {
  address: AddressInput!
  name: String!
  code: BusinessIdentifierCode!
}

input AddressInput {
  addressLine1: String
  addressLine2: String
  city: String
  country: CountryAlpha3Code!
  postalCode: PostalCode
}

```

When the plugin encounters `BusinessIdentifierCode` and `CountryAlpha3Code` those are custom scalars, so the docs are clear and the `scalarSchemas` config should be used, something like:

```
config:
  schema: yup
  scalarSchemas:
    BusinessIdentifierCode: yup.string()
    CountryAlpha3Code: yup.string().max(3)
```


However `AddressInput` is also a field of `BusinessInput`, but it is not a Scalar, it's a GraphQL Input type.

It falls through https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/blob/main/src/yup/index.ts#L263 because it's not a scalar type. You can still add it to `scalarSchemas`, but you have to know if the input is an enum or not as enum schemas are not callable.


I think it would be possible to make the plugin smart enough to know when it had generated a type for an input already an use it in this case, without the need for config at all, but I haven't worked through it all yet.
