### ISSUE TITLE
[Help] GraphQL-Ruby InputSchema generation in zod changed behavior for non-nullable fields

### ISSUE THREAD

**Issue by midorizemi** [Code-Hex/graphql-codegen-typescript-validation-schema#445]
We're working on an API with GraphQL-Ruby and a front-end using TypeScript React. To bridge the two, we use `graphql-codegen` to derive zod type definitions from our `schema.graphql`.

Upon updating, we noticed a change in the way zod InputSchema is generated.

## Original GraphQL Mutation:
```graphql
"""
Autogenerated input type of CreateComment
"""
input CreateCommentInput {
  body: String!

  """
  A unique identifier for the client performing the mutation.
  """
  clientMutationId: String
  resourceId: ID = null
}

type Mutation {
    ...
  createComment(
    """
    Parameters for CreateComment
    """
    input: CreateCommentInput!
  ): CreateCommentPayload
}
```
## New zod InputSchema generation:
```ts
...
export function CreateCommentInputSchema(): z.ZodObject<Properties<CreateCommentInput>> {
  return z.object({
    body: definedNonNullAnySchema,
    clientMutationId: definedNonNullAnySchema.nullish(),
    resourceId: definedNonNullAnySchema.nullish()
  })
}
```
## Expected (previous) zod InputSchema generation:
```ts
...
export function CreateCommentInputSchema(): z.ZodObject<Properties<CreateCommentInput>> {
  return z.object<Properties<CreateCommentInput>>({
    body: z.string().min(1),
    clientMutationId: z.string().nullish(),
    resourceId: z.string().nullish()
  })
}
```
For fields marked as required in our GraphQL input (`!`), the newly generated zod schema now uses `definedNonNullAnySchema`. This behavior reminds me of an issue: [graphql-codegen-typescript-validation-schema#17](https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/issues/17). However, for our use case, we'd prefer the prior behavior.

## Version Information:
- graphql-codegen: 2.16.5
- graphql-codegen-typescript-validation-schema: 0.11.1
- typescript: 4.9.5
- zod: 3.21.4

## codegen.yml
```yml
...
  ./src/graphql/generated/zodSchema.ts:
    plugins:
      - typescript
      - typescript-validation-schema
    config:
      schema: zod
      strictScalars: true
      directives:
        constraint:
          minLength: ["min", "$1", "$1文字以上入力してください"]
          maxLength: ["max", "$1", "$1文字以内で入力してください"]
      scalars:
        Date: string
        DateTime: string
        File: File
        ISO8601Date: string
        ISO8601DateTime: string
        Id: string
      scalarSchemas:
        File: z.object(File)
      notAllowEmptyString: true
```

**Comment by Code-Hex** [comment]
@midorizemi Hi! Thanks for making this issue.

I tried to generate code in my local environment. However, I cannot reproduce your issue.

```yml
example/types.ts:
    plugins:
      - typescript
    config:
      scalars:
        Date: string
        DateTime: string
        File: File
        ISO8601Date: string
        ISO8601DateTime: string
        Id: string
example/zod/schemas.ts:
    plugins:
      - ./dist/main/index.js:
          schema: zod
          importFrom: ../types
          # withObjectType: true
          directives:
            constraint:
              minLength: ["min", "$1", "$1文字以上入力してください"]
              maxLength: ["max", "$1", "$1文字以内で入力してください"]
          scalars:
            Date: string
            DateTime: string
            File: File
            ISO8601Date: string
            ISO8601DateTime: string
            Id: string
          scalarSchemas:
            File: z.object(File)
          notAllowEmptyString: true
```

### Versions

- graphql-codegen: 5.0.0 (this is different)
- typescript: 5.1.6
- zod: 3.21.4

### Generated code

```ts
import { z } from 'zod'
import { CreateCommentInput } from '../types'

type Properties<T> = Required<{
  [K in keyof T]: z.ZodType<T[K], any, T[K]>;
}>;

type definedNonNullAny = {};

export const isDefinedNonNullAny = (v: any): v is definedNonNullAny => v !== undefined && v !== null;

export const definedNonNullAnySchema = z.any().refine((v) => isDefinedNonNullAny(v));

export function CreateCommentInputSchema(): z.ZodObject<Properties<CreateCommentInput>> {
  return z.object({
    body: z.string().min(1),
    clientMutationId: z.string().nullish(),
    resourceId: z.string().nullish()
  })
}
```
