### ISSUE TITLE
Constraints from directives are not applied to generated zod schema

### ISSUE THREAD

**Issue by llwire** [Code-Hex/graphql-codegen-typescript-validation-schema#750]
The plugin isn't applying the constraints from the GraphQL input definition to the generated zod schema. Based on what I can tell from the codebase, everything seems to be configured correctly. Am I missing something here?

Current config definitions:

```yaml
overwrite: true
generates:
  ...
  ./src/graphql/__generated__/partnerApiValidations.ts:
    schema: '...'
    config:
      schema: zod
      strictScalars: true
      directives:
        constraint:
          min: min
          max: max
          pattern: [regex, /$1/, "invalid input"]
          startsWith: [regex, /^$1/, "invalid input"]
          format:
            email: email
            uri: url
            emoji: emoji
    plugins:
      - typescript-validation-schema
```

Directive definition:

```graphql
  directive @constraint(min: Int, max: Int, pattern: String, startsWith: String, format: ConstraintFormat) on INPUT_FIELD_DEFINITION

  enum ConstraintFormat {
    email
    uri
  }
```

Directive used as:

```graphql
  input ProductCreateInput {
    title: String! @constraint(min: 5, max: 80)
  }
```

Codegen output:

```javascript
export function ProductCreateInputSchema(): z.ZodObject<Properties<ProductCreateInput>> {
  return z.object({
    title: z.string()
  })
}
```

**Comment by Code-Hex** [comment]
@llwire I'm sorry for the delay. Your code generated what you expected properly with my local environment.

```ts
export function ProductCreateInputSchema(): z.ZodObject<Properties<ProductCreateInput>> {
    return z.object({
     title: z.string().min(5).max(80)
    })
  }
```

I would like you to check again to see if other settings are affecting it, or if the schema has been merged into one file.

**Comment by llwire** [comment]
Thanks for the response @Code-Hex!

I did some digging and the issues was on my side. I was pointing codegen to the api schema rather than the actual schema file, ie. `localhost:4000/graphql` instead of `./src/graphql/schema/index.ts'. Since the directives get stripped from the server response, there was no way for the validation schema to be properly generated.

In case anyone runs into this, my complete working config looks like this: 
```yml
overwrite: true
require:
  - "ts-node/register/transpile-only"
generates:
  ./src/graphql/__generated__/partnerApiValidations.ts:
    schema: './src/graphql/api/partner/schema/index.ts'
    config:
      schema: zod
      strictScalars: true
      directives:
        constraint:
          min: min
          max: max
          pattern: [regex, /$1/, "invalid input"]
          startsWith: [regex, /^$1/, "invalid input"]
          format:
            email: email
            uri: url
            emoji: emoji
    plugins:
      - typescript-validation-schema
```

The `require` setting was necessary for codegen to properly read the schema from the TS file.
